# Generated by Django 3.0.5 on 2022-01-13 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20220112_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='addr',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lot',
            name='pr_k',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
