# Generated by Django 3.0.5 on 2022-01-13 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20220113_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lot',
            name='addr',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='pr_k',
        ),
    ]
