# Generated by Django 3.0.5 on 2022-01-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20220113_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ropsten', models.URLField(default=None)),
                ('address', models.CharField(blank=True, default=None, max_length=80, null=True)),
                ('private_key', models.CharField(blank=True, default=None, max_length=80, null=True)),
                ('new_wallet', models.BooleanField(default=False)),
            ],
        ),
    ]
