# Generated by Django 3.0.5 on 2022-01-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_wal_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wal',
            name='address',
            field=models.TextField(blank=True, default=None, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='wal',
            name='private_key',
            field=models.TextField(blank=True, default=None, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='wal',
            name='ropsten',
            field=models.TextField(default=None, max_length=80, null=True),
        ),
    ]
